### ISSUE TITLE
User is not defined

### ISSUE THREAD

**Issue by gofreddo** [leonardomso/graphql-mongodb-server#1]
I followed the directions in the readme.md.  The following query returns the following error.

'''{
  users {
    id
  }
}
'''

'''{
  "errors": [
    {
      "message": "User is not defined",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "users"
      ]
    }
  ],
  "data": {
    "users": null
  }
}'''

**Comment by leonardomso** [comment]
Ifixed the error, realized that I forgot to export the User model from the models folder to resolvers. 😀
