### ISSUE TITLE
How to sort / filter the posts

### ISSUE THREAD

**Issue by AntoninSlejska** [leonardomso/graphql-mongodb-server#16]
I have a simple request like this:

`query {Posts{_id title date {published}}}`

How can I sort the posts e.g. by publishing date and limit the number of posts? And how can I filter the posts, e.g. that I get only posts older than some date?

**Comment by guiguetz** [comment]
Hi! You should check out [this link](https://graphql.org/learn/pagination/). I'm new to GraphQL and running onto the same issues, but they explain in a pretty simple way.

but basically your query should become something like

```
query {
  Posts(first: 10, offset: $cursor) {
    _id
    title
    date {
      published
    }
  }
}
```
Where you get $cursor controlled by your resolver indicating where should your pagination work.

**Comment by AntoninSlejska** [comment]
Thanks Bruno!
