### ISSUE TITLE
how to create post with graphql ?

### ISSUE THREAD

**Issue by menzil** [leonardomso/graphql-mongodb-server#6]
I`m a new starter for express and graphql, thank you for this demo project.
I can create user,query user,users and update user, but I dont know how to create post with graphql.

**Comment by leonardomso** [comment]
All the queries and mutations at this project are pretty similar, you don't know how to make a mutation to create a post, that's it?

**Comment by menzil** [comment]
> All the queries and mutations at this project are pretty similar, you don't know how to make a mutation to create a post, that's it?

yes.

**Comment by leonardomso** [comment]
To create a post, your mutation it's going to be like this:

`createPost(post: { title: "First Post", body: "Body of my Post", published: true, author: 123 }) {
  title
  body
  published
  author
}`

At the Author you should pass a valid ID, otherwise it will throw you an error. I think that this mutation should work.

**Comment by menzil** [comment]
this is my users:
```json
{
  "data": {
    "users": [
      {
        "_id": "5c937c9e6b1e7720104bb8aa",
        "name": "nur",
        "age": 25,
        "email": "nur@live.cn"
      },
      {
        "_id": "5c937eb2d2a2722988b39573",
        "name": "gulber",
        "age": 20,
        "email": "gul@live.cn"
      }
    ]
  }
}```

createPost: 
```graphql
mutation{
  createPost(post: 
    { title: "First Post", 
      body: "Body of my Post", 
      published: true, 
      author: "5c937eb2d2a2722988b39573" 
    }) { title body published author }
}
```
and the erro info is: 
```json
{
  "error": {
    "errors": [
      {
        "message": "Field \"author\" of type \"User!\" must have a selection of subfields. Did you mean \"author { ... }\"?",
        "locations": [
          {
            "line": 6,
            "column": 5
          }
        ]
      }
    ]
  }
}
```

**Comment by leonardomso** [comment]
That's because when you are returning the author, you should return its subfields as well, like this:

```
author {
   _id
   name
   email
}
```

**Comment by menzil** [comment]
Thank you. It was work.
```
mutation{
  createPost(post: 
    { title: "First Post", 
      body: "Body of my Post", 
      published: true, 
      author: "5c937eb2d2a2722988b39573"
    }) { title body published author {
       _id
       name
       email
    } }
}
```

**Comment by menzil** [comment]
I add some graphql query and mutation example with my practice. [graphql example with this project](https://github.com/menzil/graphql-mongodb-server/blob/master/graphql-examples.md)

**Comment by leonardomso** [comment]
Wow, nice!

**Comment by coolemur** [comment]
Hello,

and how do you insert comments in posts document?

so in mongodb you would have something like:

Post document:
id: 5cd008e071cf6d881b3a614b
comments: [ { COMMENT DATA }, { COMMENT DATA  }, { COMMENT DATA  }, ...]
...

I tried creating a post and after that creating the comment using mutations and reference ids, but this only creates two separate mongodb documents with reference field (and not a comment data inside post document).

Any ideas how to do it?
